// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountAllUsers = `-- name: AdminCountAllUsers :one
SELECT COUNT(*) FROM users WHERE role = 'user'
`

func (q *Queries) AdminCountAllUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountAllUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminListAllUsers = `-- name: AdminListAllUsers :many
SELECT id, username, email, role, create_time, is_delete
FROM users
WHERE role = 'user'
ORDER BY create_time DESC
LIMIT $1 OFFSET $2
`

type AdminListAllUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type AdminListAllUsersRow struct {
	ID         pgtype.UUID      `json:"id"`
	Username   string           `json:"username"`
	Email      string           `json:"email"`
	Role       string           `json:"role"`
	CreateTime pgtype.Timestamp `json:"createTime"`
	IsDelete   bool             `json:"isDelete"`
}

func (q *Queries) AdminListAllUsers(ctx context.Context, arg AdminListAllUsersParams) ([]AdminListAllUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListAllUsersRow
	for rows.Next() {
		var i AdminListAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Role,
			&i.CreateTime,
			&i.IsDelete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUsers = `-- name: AdminListUsers :many
SELECT id, username, email, role, create_time, is_delete
FROM users
WHERE is_delete = false AND role = 'user'
ORDER BY create_time DESC
LIMIT $1 OFFSET $2
`

type AdminListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type AdminListUsersRow struct {
	ID         pgtype.UUID      `json:"id"`
	Username   string           `json:"username"`
	Email      string           `json:"email"`
	Role       string           `json:"role"`
	CreateTime pgtype.Timestamp `json:"createTime"`
	IsDelete   bool             `json:"isDelete"`
}

func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListUsersRow
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Role,
			&i.CreateTime,
			&i.IsDelete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminLogin = `-- name: AdminLogin :one
SELECT is_delete, create_time, update_time, id, username, email, avatar, password, role, email_verified, bio, name, pending_email FROM users
WHERE username = $1 AND is_delete = false AND role = 'admin' LIMIT 1
`

func (q *Queries) AdminLogin(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, adminLogin, username)
	var i User
	err := row.Scan(
		&i.IsDelete,
		&i.CreateTime,
		&i.UpdateTime,
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Avatar,
		&i.Password,
		&i.Role,
		&i.EmailVerified,
		&i.Bio,
		&i.Name,
		&i.PendingEmail,
	)
	return i, err
}

const getPostsOverTime = `-- name: GetPostsOverTime :many
SELECT DATE_TRUNC('day', create_time)::timestamp AS date, COUNT(*) AS count
FROM posts
WHERE status <> 0
  AND create_time >= NOW() - INTERVAL '30 days'
GROUP BY DATE_TRUNC('day', create_time)
ORDER BY date
`

type GetPostsOverTimeRow struct {
	Date  pgtype.Timestamp `json:"date"`
	Count int64            `json:"count"`
}

func (q *Queries) GetPostsOverTime(ctx context.Context) ([]GetPostsOverTimeRow, error) {
	rows, err := q.db.Query(ctx, getPostsOverTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsOverTimeRow
	for rows.Next() {
		var i GetPostsOverTimeRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalComments = `-- name: GetTotalComments :one
SELECT COUNT(*) FROM comments WHERE is_delete = false
`

func (q *Queries) GetTotalComments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalComments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalPosts = `-- name: GetTotalPosts :one
SELECT COUNT(*) FROM posts WHERE status <> 0
`

func (q *Queries) GetTotalPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalUsers = `-- name: GetTotalUsers :one
SELECT COUNT(*) FROM users WHERE is_delete = false AND role = 'user'
`

func (q *Queries) GetTotalUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUsersOverTime = `-- name: GetUsersOverTime :many
SELECT DATE_TRUNC('day', create_time)::timestamp AS date, COUNT(*) AS count
FROM users
WHERE is_delete = false AND role = 'user'
  AND create_time >= NOW() - INTERVAL '30 days'
GROUP BY DATE_TRUNC('day', create_time)
ORDER BY date
`

type GetUsersOverTimeRow struct {
	Date  pgtype.Timestamp `json:"date"`
	Count int64            `json:"count"`
}

func (q *Queries) GetUsersOverTime(ctx context.Context) ([]GetUsersOverTimeRow, error) {
	rows, err := q.db.Query(ctx, getUsersOverTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersOverTimeRow
	for rows.Next() {
		var i GetUsersOverTimeRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleUserStatus = `-- name: ToggleUserStatus :one
UPDATE users
SET is_delete = NOT is_delete,
    update_time = now()
WHERE id = $1
RETURNING is_delete
`

func (q *Queries) ToggleUserStatus(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, toggleUserStatus, id)
	var is_delete bool
	err := row.Scan(&is_delete)
	return is_delete, err
}
