// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAuditLog = `-- name: AddAuditLog :exec
INSERT INTO public.audit_logs
("action", entity_name, old_value, new_value, create_by)
VALUES($1, $2, $3, $4, $5)
`

type AddAuditLogParams struct {
	Action     string      `json:"action"`
	EntityName string      `json:"entityName"`
	OldValue   []byte      `json:"oldValue"`
	NewValue   []byte      `json:"newValue"`
	CreateBy   pgtype.UUID `json:"createBy"`
}

func (q *Queries) AddAuditLog(ctx context.Context, arg AddAuditLogParams) error {
	_, err := q.db.Exec(ctx, addAuditLog,
		arg.Action,
		arg.EntityName,
		arg.OldValue,
		arg.NewValue,
		arg.CreateBy,
	)
	return err
}
