// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comment.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCommentsByPost = `-- name: CountCommentsByPost :one
SELECT COUNT(*) FROM comments
WHERE post_id = $1 AND is_delete = false
`

func (q *Queries) CountCommentsByPost(ctx context.Context, postID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByPost, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
WITH new_comment AS (
    INSERT INTO comments
        (user_id, post_id, content, reply_to)
    VALUES
        ($1, $2, $3, $4)
    RETURNING is_delete, create_time, update_time, id, user_id, post_id, content, reply_to
)
SELECT
    c.is_delete, c.create_time, c.update_time, c.id, c.user_id, c.post_id, c.content, c.reply_to,
    u.avatar,
    u.username
FROM new_comment c
INNER JOIN users u
    ON c.user_id = u.id
`

type CreateCommentParams struct {
	UserID  pgtype.UUID `json:"userId"`
	PostID  pgtype.UUID `json:"postId"`
	Content string      `json:"content"`
	ReplyTo pgtype.UUID `json:"replyTo"`
}

type CreateCommentRow struct {
	IsDelete   bool             `json:"isDelete"`
	CreateTime pgtype.Timestamp `json:"createTime"`
	UpdateTime pgtype.Timestamp `json:"updateTime"`
	ID         pgtype.UUID      `json:"id"`
	UserID     pgtype.UUID      `json:"userId"`
	PostID     pgtype.UUID      `json:"postId"`
	Content    string           `json:"content"`
	ReplyTo    pgtype.UUID      `json:"replyTo"`
	Avatar     pgtype.Text      `json:"avatar"`
	Username   string           `json:"username"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.UserID,
		arg.PostID,
		arg.Content,
		arg.ReplyTo,
	)
	var i CreateCommentRow
	err := row.Scan(
		&i.IsDelete,
		&i.CreateTime,
		&i.UpdateTime,
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.Content,
		&i.ReplyTo,
		&i.Avatar,
		&i.Username,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :one
WITH deleted_comment AS (
    UPDATE comments
    SET is_delete = true
    WHERE comments.id = $1
    RETURNING is_delete, create_time, update_time, id, user_id, post_id, content, reply_to
)
SELECT
    deleted_comment.is_delete, deleted_comment.create_time, deleted_comment.update_time, deleted_comment.id, deleted_comment.user_id, deleted_comment.post_id, deleted_comment.content, deleted_comment.reply_to,
    u.avatar,
    u.username
FROM deleted_comment
JOIN users AS u
    ON deleted_comment.user_id = u.id
`

type DeleteCommentRow struct {
	IsDelete   bool             `json:"isDelete"`
	CreateTime pgtype.Timestamp `json:"createTime"`
	UpdateTime pgtype.Timestamp `json:"updateTime"`
	ID         pgtype.UUID      `json:"id"`
	UserID     pgtype.UUID      `json:"userId"`
	PostID     pgtype.UUID      `json:"postId"`
	Content    string           `json:"content"`
	ReplyTo    pgtype.UUID      `json:"replyTo"`
	Avatar     pgtype.Text      `json:"avatar"`
	Username   string           `json:"username"`
}

func (q *Queries) DeleteComment(ctx context.Context, id pgtype.UUID) (DeleteCommentRow, error) {
	row := q.db.QueryRow(ctx, deleteComment, id)
	var i DeleteCommentRow
	err := row.Scan(
		&i.IsDelete,
		&i.CreateTime,
		&i.UpdateTime,
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.Content,
		&i.ReplyTo,
		&i.Avatar,
		&i.Username,
	)
	return i, err
}

const getCommentsByPost = `-- name: GetCommentsByPost :many
SELECT
    c.is_delete,
    c.update_time,
    c.id,
    c.user_id,
    c.post_id,
    c.content,
    c.reply_to,
    u.avatar,
    u.username,
    EXTRACT(EPOCH FROM c.create_time)::bigint AS create_time
FROM comments c
INNER JOIN users u ON c.user_id = u.id
WHERE c.post_id = $1
  AND c.is_delete = false
ORDER BY c.create_time DESC, c.id DESC
LIMIT $2 OFFSET $3
`

type GetCommentsByPostParams struct {
	PostID pgtype.UUID `json:"postId"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetCommentsByPostRow struct {
	IsDelete   bool             `json:"isDelete"`
	UpdateTime pgtype.Timestamp `json:"updateTime"`
	ID         pgtype.UUID      `json:"id"`
	UserID     pgtype.UUID      `json:"userId"`
	PostID     pgtype.UUID      `json:"postId"`
	Content    string           `json:"content"`
	ReplyTo    pgtype.UUID      `json:"replyTo"`
	Avatar     pgtype.Text      `json:"avatar"`
	Username   string           `json:"username"`
	CreateTime int64            `json:"createTime"`
}

func (q *Queries) GetCommentsByPost(ctx context.Context, arg GetCommentsByPostParams) ([]GetCommentsByPostRow, error) {
	rows, err := q.db.Query(ctx, getCommentsByPost, arg.PostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsByPostRow
	for rows.Next() {
		var i GetCommentsByPostRow
		if err := rows.Scan(
			&i.IsDelete,
			&i.UpdateTime,
			&i.ID,
			&i.UserID,
			&i.PostID,
			&i.Content,
			&i.ReplyTo,
			&i.Avatar,
			&i.Username,
			&i.CreateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
WITH updated_comment AS (
    UPDATE comments
    SET
        update_time = NOW(),
        content = $2
    WHERE comments.id = $1
    RETURNING is_delete, create_time, update_time, id, user_id, post_id, content, reply_to
)
SELECT
    updated_comment.is_delete, updated_comment.create_time, updated_comment.update_time, updated_comment.id, updated_comment.user_id, updated_comment.post_id, updated_comment.content, updated_comment.reply_to,
    u.avatar,
    u.username
FROM updated_comment
JOIN users AS u
    ON updated_comment.user_id = u.id
`

type UpdateCommentParams struct {
	ID      pgtype.UUID `json:"id"`
	Content string      `json:"content"`
}

type UpdateCommentRow struct {
	IsDelete   bool             `json:"isDelete"`
	CreateTime pgtype.Timestamp `json:"createTime"`
	UpdateTime pgtype.Timestamp `json:"updateTime"`
	ID         pgtype.UUID      `json:"id"`
	UserID     pgtype.UUID      `json:"userId"`
	PostID     pgtype.UUID      `json:"postId"`
	Content    string           `json:"content"`
	ReplyTo    pgtype.UUID      `json:"replyTo"`
	Avatar     pgtype.Text      `json:"avatar"`
	Username   string           `json:"username"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (UpdateCommentRow, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Content)
	var i UpdateCommentRow
	err := row.Scan(
		&i.IsDelete,
		&i.CreateTime,
		&i.UpdateTime,
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.Content,
		&i.ReplyTo,
		&i.Avatar,
		&i.Username,
	)
	return i, err
}
