// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comment.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments
    (user_id, post_id, content, reply_to)
VALUES
    ($1, $2, $3, $4)
RETURNING is_delete, create_time, update_time, id, user_id, post_id, content, reply_to
`

type CreateCommentParams struct {
	UserID  pgtype.UUID
	PostID  pgtype.UUID
	Content string
	ReplyTo pgtype.UUID
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.UserID,
		arg.PostID,
		arg.Content,
		arg.ReplyTo,
	)
	var i Comment
	err := row.Scan(
		&i.IsDelete,
		&i.CreateTime,
		&i.UpdateTime,
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.Content,
		&i.ReplyTo,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :one
UPDATE comments
SET is_deleted = true
WHERE id = $1
RETURNING is_delete, create_time, update_time, id, user_id, post_id, content, reply_to
`

func (q *Queries) DeleteComment(ctx context.Context, id pgtype.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, deleteComment, id)
	var i Comment
	err := row.Scan(
		&i.IsDelete,
		&i.CreateTime,
		&i.UpdateTime,
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.Content,
		&i.ReplyTo,
	)
	return i, err
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET
    update_time = NOW(),
    content = $2
WHERE id = $1
RETURNING is_delete, create_time, update_time, id, user_id, post_id, content, reply_to
`

type UpdateCommentParams struct {
	ID      pgtype.UUID
	Content string
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.IsDelete,
		&i.CreateTime,
		&i.UpdateTime,
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.Content,
		&i.ReplyTo,
	)
	return i, err
}
