// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compose.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompose = `-- name: CreateCompose :exec
INSERT INTO composes
(user_id, post_id)
VALUES($1, $2)
`

type CreateComposeParams struct {
	UserID pgtype.UUID
	PostID pgtype.UUID
}

func (q *Queries) CreateCompose(ctx context.Context, arg CreateComposeParams) error {
	_, err := q.db.Exec(ctx, createCompose, arg.UserID, arg.PostID)
	return err
}
