// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dm.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMessage = `-- name: AddMessage :one
INSERT INTO direct_messages
("from", "to", message)
VALUES ($1, $2, $3)
RETURNING is_delete, create_time, update_time, id, "from", "to", message
`

type AddMessageParams struct {
	From    pgtype.UUID `json:"from"`
	To      pgtype.UUID `json:"to"`
	Message pgtype.Text `json:"message"`
}

func (q *Queries) AddMessage(ctx context.Context, arg AddMessageParams) (DirectMessage, error) {
	row := q.db.QueryRow(ctx, addMessage, arg.From, arg.To, arg.Message)
	var i DirectMessage
	err := row.Scan(
		&i.IsDelete,
		&i.CreateTime,
		&i.UpdateTime,
		&i.ID,
		&i.From,
		&i.To,
		&i.Message,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :one
UPDATE public.direct_messages
SET update_time=NOW(), is_delete = true
WHERE id=$1
RETURNING is_delete, create_time, update_time, id, "from", "to", message
`

func (q *Queries) DeleteMessage(ctx context.Context, id pgtype.UUID) (DirectMessage, error) {
	row := q.db.QueryRow(ctx, deleteMessage, id)
	var i DirectMessage
	err := row.Scan(
		&i.IsDelete,
		&i.CreateTime,
		&i.UpdateTime,
		&i.ID,
		&i.From,
		&i.To,
		&i.Message,
	)
	return i, err
}

const getConversationMessages = `-- name: GetConversationMessages :many
SELECT dm.is_delete, dm.create_time, dm.update_time, dm.id, dm."from", dm."to", dm.message
FROM direct_messages dm
WHERE ((dm."from" = $1 AND dm."to" = $2) OR (dm."from" = $2 AND dm."to" = $1))
  AND dm.is_delete = false
ORDER BY dm.create_time ASC
LIMIT $3
`

type GetConversationMessagesParams struct {
	From  pgtype.UUID `json:"from"`
	To    pgtype.UUID `json:"to"`
	Limit int32       `json:"limit"`
}

func (q *Queries) GetConversationMessages(ctx context.Context, arg GetConversationMessagesParams) ([]DirectMessage, error) {
	rows, err := q.db.Query(ctx, getConversationMessages, arg.From, arg.To, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DirectMessage
	for rows.Next() {
		var i DirectMessage
		if err := rows.Scan(
			&i.IsDelete,
			&i.CreateTime,
			&i.UpdateTime,
			&i.ID,
			&i.From,
			&i.To,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessages = `-- name: GetMessages :many
SELECT is_delete, create_time, update_time, id, "from", "to", message
FROM direct_messages dm
WHERE dm.create_time < $1
LIMIT $2
`

type GetMessagesParams struct {
	CreateTime pgtype.Timestamp `json:"createTime"`
	Limit      int32            `json:"limit"`
}

func (q *Queries) GetMessages(ctx context.Context, arg GetMessagesParams) ([]DirectMessage, error) {
	rows, err := q.db.Query(ctx, getMessages, arg.CreateTime, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DirectMessage
	for rows.Next() {
		var i DirectMessage
		if err := rows.Scan(
			&i.IsDelete,
			&i.CreateTime,
			&i.UpdateTime,
			&i.ID,
			&i.From,
			&i.To,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE public.direct_messages
SET update_time=NOW(), message=$2
WHERE id=$1
RETURNING is_delete, create_time, update_time, id, "from", "to", message
`

type UpdateMessageParams struct {
	ID      pgtype.UUID `json:"id"`
	Message pgtype.Text `json:"message"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (DirectMessage, error) {
	row := q.db.QueryRow(ctx, updateMessage, arg.ID, arg.Message)
	var i DirectMessage
	err := row.Scan(
		&i.IsDelete,
		&i.CreateTime,
		&i.UpdateTime,
		&i.ID,
		&i.From,
		&i.To,
		&i.Message,
	)
	return i, err
}
