// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verification.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerification = `-- name: CreateEmailVerification :exec
INSERT INTO email_verifications
(user_id, "token", expires_at)
VALUES($1, $2, $3)
`

type CreateEmailVerificationParams struct {
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error {
	_, err := q.db.Exec(ctx, createEmailVerification, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}

const getUserByToken = `-- name: GetUserByToken :exec
SELECT id, user_id, token, expires_at, created_at FROM email_verifications
WHERE token = $1 AND expires_at < now()
`

func (q *Queries) GetUserByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, getUserByToken, token)
	return err
}
