// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follow.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFollowers = `-- name: CountFollowers :one
SELECT COUNT(*) FROM follows WHERE following_id = $1
`

func (q *Queries) CountFollowers(ctx context.Context, followingID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowers, followingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowing = `-- name: CountFollowing :one
SELECT COUNT(*) FROM follows WHERE follower_id = $1
`

func (q *Queries) CountFollowing(ctx context.Context, followerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowing, followerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const followUser = `-- name: FollowUser :exec
INSERT INTO follows (follower_id, following_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type FollowUserParams struct {
	FollowerID  pgtype.UUID `json:"followerId"`
	FollowingID pgtype.UUID `json:"followingId"`
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.Exec(ctx, followUser, arg.FollowerID, arg.FollowingID)
	return err
}

const getFollowers = `-- name: GetFollowers :many
SELECT u.is_delete, u.create_time, u.update_time, u.id, u.username, u.email, u.avatar, u.password, u.role, u.email_verified, u.bio, u.name, u.pending_email FROM users u
JOIN follows f ON f.follower_id = u.id
WHERE f.following_id = $1 AND u.is_delete = false
ORDER BY f.create_time DESC
`

func (q *Queries) GetFollowers(ctx context.Context, followingID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getFollowers, followingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.IsDelete,
			&i.CreateTime,
			&i.UpdateTime,
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Avatar,
			&i.Password,
			&i.Role,
			&i.EmailVerified,
			&i.Bio,
			&i.Name,
			&i.PendingEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowing = `-- name: GetFollowing :many
SELECT u.is_delete, u.create_time, u.update_time, u.id, u.username, u.email, u.avatar, u.password, u.role, u.email_verified, u.bio, u.name, u.pending_email FROM users u
JOIN follows f ON f.following_id = u.id
WHERE f.follower_id = $1 AND u.is_delete = false
ORDER BY f.create_time DESC
`

func (q *Queries) GetFollowing(ctx context.Context, followerID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getFollowing, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.IsDelete,
			&i.CreateTime,
			&i.UpdateTime,
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Avatar,
			&i.Password,
			&i.Role,
			&i.EmailVerified,
			&i.Bio,
			&i.Name,
			&i.PendingEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS (
  SELECT 1 FROM follows WHERE follower_id = $1 AND following_id = $2
)
`

type IsFollowingParams struct {
	FollowerID  pgtype.UUID `json:"followerId"`
	FollowingID pgtype.UUID `json:"followingId"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FollowingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM follows WHERE follower_id = $1 AND following_id = $2
`

type UnfollowUserParams struct {
	FollowerID  pgtype.UUID `json:"followerId"`
	FollowingID pgtype.UUID `json:"followingId"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FollowerID, arg.FollowingID)
	return err
}
