// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: like.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLike = `-- name: DeleteLike :one
DELETE FROM likes
WHERE user_id = $1
  AND post_id = $2
  RETURNING user_id, post_id, create_time
`

type DeleteLikeParams struct {
	UserID pgtype.UUID
	PostID pgtype.UUID
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) (Like, error) {
	row := q.db.QueryRow(ctx, deleteLike, arg.UserID, arg.PostID)
	var i Like
	err := row.Scan(&i.UserID, &i.PostID, &i.CreateTime)
	return i, err
}

const like = `-- name: Like :one
INSERT INTO likes
(user_id, post_id, create_time)
VALUES($1, $2, now())
  RETURNING user_id, post_id, create_time
`

type LikeParams struct {
	UserID pgtype.UUID
	PostID pgtype.UUID
}

func (q *Queries) Like(ctx context.Context, arg LikeParams) (Like, error) {
	row := q.db.QueryRow(ctx, like, arg.UserID, arg.PostID)
	var i Like
	err := row.Scan(&i.UserID, &i.PostID, &i.CreateTime)
	return i, err
}
