// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         pgtype.UUID      `json:"id"`
	Action     string           `json:"action"`
	EntityName string           `json:"entityName"`
	OldValue   []byte           `json:"oldValue"`
	NewValue   []byte           `json:"newValue"`
	CreateBy   pgtype.UUID      `json:"createBy"`
	CreateTime pgtype.Timestamp `json:"createTime"`
}

type Comment struct {
	IsDelete   bool             `json:"isDelete"`
	CreateTime pgtype.Timestamp `json:"createTime"`
	UpdateTime pgtype.Timestamp `json:"updateTime"`
	ID         pgtype.UUID      `json:"id"`
	UserID     pgtype.UUID      `json:"userId"`
	PostID     pgtype.UUID      `json:"postId"`
	Content    string           `json:"content"`
	ReplyTo    pgtype.UUID      `json:"replyTo"`
}

type Compose struct {
	UserID     pgtype.UUID      `json:"userId"`
	PostID     pgtype.UUID      `json:"postId"`
	CreateTime pgtype.Timestamp `json:"createTime"`
	Role       string           `json:"role"`
}

type Follow struct {
	FollowerID  pgtype.UUID      `json:"followerId"`
	FollowingID pgtype.UUID      `json:"followingId"`
	CreateTime  pgtype.Timestamp `json:"createTime"`
}

type Like struct {
	UserID     pgtype.UUID      `json:"userId"`
	PostID     pgtype.UUID      `json:"postId"`
	CreateTime pgtype.Timestamp `json:"createTime"`
}

type Notification struct {
	ID          pgtype.UUID        `json:"id"`
	RecipientID pgtype.UUID        `json:"recipientId"`
	ActorID     pgtype.UUID        `json:"actorId"`
	Type        string             `json:"type"`
	EntityID    pgtype.UUID        `json:"entityId"`
	ReadAt      pgtype.Timestamptz `json:"readAt"`
	CreateTime  pgtype.Timestamptz `json:"createTime"`
}

type Post struct {
	CreateTime  pgtype.Timestamp `json:"createTime"`
	UpdateTime  pgtype.Timestamp `json:"updateTime"`
	ID          pgtype.UUID      `json:"id"`
	Title       pgtype.Text      `json:"title"`
	Content     pgtype.Text      `json:"content"`
	Thumbnail   pgtype.Text      `json:"thumbnail"`
	Description pgtype.Text      `json:"description"`
	Status      int32            `json:"status"`
}

type Repost struct {
	UserID pgtype.UUID `json:"userId"`
	PostID pgtype.UUID `json:"postId"`
}

type SoftDelete struct {
	IsDelete bool `json:"isDelete"`
}

type TimeLog struct {
	CreateTime pgtype.Timestamp `json:"createTime"`
	UpdateTime pgtype.Timestamp `json:"updateTime"`
}

type User struct {
	IsDelete      bool             `json:"isDelete"`
	CreateTime    pgtype.Timestamp `json:"createTime"`
	UpdateTime    pgtype.Timestamp `json:"updateTime"`
	ID            pgtype.UUID      `json:"id"`
	Username      string           `json:"username"`
	Email         string           `json:"email"`
	Avatar        pgtype.Text      `json:"avatar"`
	Password      pgtype.Text      `json:"password"`
	Role          string           `json:"role"`
	EmailVerified bool             `json:"emailVerified"`
	Bio           pgtype.Text      `json:"bio"`
	Name          pgtype.Text      `json:"name"`
	PendingEmail  pgtype.Text      `json:"pendingEmail"`
}
