// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         pgtype.UUID
	Action     string
	EntityName string
	OldValue   pgtype.Text
	NewValue   pgtype.Text
	CreateBy   pgtype.UUID
	CreateTime pgtype.Timestamp
}

type Comment struct {
	IsDelete   bool
	CreateTime pgtype.Timestamp
	UpdateTime pgtype.Timestamp
	UserID     pgtype.UUID
	PostID     pgtype.UUID
	Cotent     pgtype.Text
}

type EmailVerification struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Like struct {
	UserID     pgtype.UUID
	PostID     pgtype.UUID
	CreateTime pgtype.Timestamp
}

type Post struct {
	IsDelete   bool
	CreateTime pgtype.Timestamp
	UpdateTime pgtype.Timestamp
	ID         pgtype.UUID
	Title      string
	Content    pgtype.Text
}

type Repost struct {
	UserID pgtype.UUID
	PostID pgtype.UUID
}

type SoftDelete struct {
	IsDelete bool
}

type TimeLog struct {
	CreateTime pgtype.Timestamp
	UpdateTime pgtype.Timestamp
}

type User struct {
	IsDelete      bool
	CreateTime    pgtype.Timestamp
	UpdateTime    pgtype.Timestamp
	ID            pgtype.UUID
	Username      string
	Email         string
	Avatar        pgtype.Text
	Password      pgtype.Text
	Role          string
	EmailVerified bool
}
