// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE recipient_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, recipientID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (recipient_id, actor_id, type, entity_id)
VALUES ($1, $2, $3, $4)
RETURNING id, recipient_id, actor_id, type, entity_id, read_at, create_time
`

type CreateNotificationParams struct {
	RecipientID pgtype.UUID `json:"recipientId"`
	ActorID     pgtype.UUID `json:"actorId"`
	Type        string      `json:"type"`
	EntityID    pgtype.UUID `json:"entityId"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.RecipientID,
		arg.ActorID,
		arg.Type,
		arg.EntityID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.ActorID,
		&i.Type,
		&i.EntityID,
		&i.ReadAt,
		&i.CreateTime,
	)
	return i, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, recipient_id, actor_id, type, entity_id, read_at, create_time FROM notifications WHERE id = $1
`

func (q *Queries) GetNotification(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.ActorID,
		&i.Type,
		&i.EntityID,
		&i.ReadAt,
		&i.CreateTime,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, recipient_id, actor_id, type, entity_id, read_at, create_time FROM notifications
WHERE recipient_id = $1
ORDER BY create_time DESC
LIMIT $2
`

type ListNotificationsParams struct {
	RecipientID pgtype.UUID `json:"recipientId"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.RecipientID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.ActorID,
			&i.Type,
			&i.EntityID,
			&i.ReadAt,
			&i.CreateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET read_at = now() WHERE id = $1
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationRead, id)
	return err
}
