// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    id,
    status
)
VALUES (
    gen_random_uuid(),
    1
)
RETURNING create_time, update_time, id, title, content, thumbnail, description, status
`

func (q *Queries) CreatePost(ctx context.Context) (Post, error) {
	row := q.db.QueryRow(ctx, createPost)
	var i Post
	err := row.Scan(
		&i.CreateTime,
		&i.UpdateTime,
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Thumbnail,
		&i.Description,
		&i.Status,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET
    update_time = now(),
    title = $2,
    content = $3,
    description = $4,
    thumbnail = $5
WHERE id = $1
RETURNING create_time, update_time, id, title, content, thumbnail, description, status
`

type UpdatePostParams struct {
	ID          pgtype.UUID
	Title       pgtype.Text
	Content     pgtype.Text
	Description pgtype.Text
	Thumbnail   pgtype.Text
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Description,
		arg.Thumbnail,
	)
	var i Post
	err := row.Scan(
		&i.CreateTime,
		&i.UpdateTime,
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Thumbnail,
		&i.Description,
		&i.Status,
	)
	return i, err
}

const updatePostStatus = `-- name: UpdatePostStatus :one
UPDATE posts
SET
    status = $2,
    update_time = now()
WHERE id = $1
RETURNING create_time, update_time, id, title, content, thumbnail, description, status
`

type UpdatePostStatusParams struct {
	ID     pgtype.UUID
	Status int32
}

func (q *Queries) UpdatePostStatus(ctx context.Context, arg UpdatePostStatusParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePostStatus, arg.ID, arg.Status)
	var i Post
	err := row.Scan(
		&i.CreateTime,
		&i.UpdateTime,
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Thumbnail,
		&i.Description,
		&i.Status,
	)
	return i, err
}
