// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReport = `-- name: AddReport :one
INSERT INTO reports
(reporter_id, reported_user_id, reason, details, status)
VALUES ($1, $2, $3, $4, 0)
RETURNING id, reporter_id, reported_user_id, reason, details, status, resolved_by, resolved_at, create_time
`

type AddReportParams struct {
	ReporterID     pgtype.UUID `json:"reporterId"`
	ReportedUserID pgtype.UUID `json:"reportedUserId"`
	Reason         string      `json:"reason"`
	Details        pgtype.Text `json:"details"`
}

func (q *Queries) AddReport(ctx context.Context, arg AddReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, addReport,
		arg.ReporterID,
		arg.ReportedUserID,
		arg.Reason,
		arg.Details,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ReportedUserID,
		&i.Reason,
		&i.Details,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreateTime,
	)
	return i, err
}

const countReports = `-- name: CountReports :one
SELECT COUNT(*) FROM reports
`

func (q *Queries) CountReports(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countReports)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReports = `-- name: GetReports :many
SELECT
    rp.id,
    reporter.username AS reporter_username,
    reported.username AS reported_username,
    resolver.username AS resolved_by_username,
    rp.reason,
    rp.details,
    rp.status
FROM reports rp
INNER JOIN users reporter
    ON rp.reporter_id = reporter.id
LEFT JOIN users reported
    ON rp.reported_user_id = reported.id
LEFT JOIN users resolver
    ON rp.resolved_by = resolver.id
ORDER BY rp.create_time DESC
LIMIT $1 OFFSET $2
`

type GetReportsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetReportsRow struct {
	ID                 pgtype.UUID `json:"id"`
	ReporterUsername   string      `json:"reporterUsername"`
	ReportedUsername   pgtype.Text `json:"reportedUsername"`
	ResolvedByUsername pgtype.Text `json:"resolvedByUsername"`
	Reason             string      `json:"reason"`
	Details            pgtype.Text `json:"details"`
	Status             int32       `json:"status"`
}

func (q *Queries) GetReports(ctx context.Context, arg GetReportsParams) ([]GetReportsRow, error) {
	rows, err := q.db.Query(ctx, getReports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportsRow
	for rows.Next() {
		var i GetReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReporterUsername,
			&i.ReportedUsername,
			&i.ResolvedByUsername,
			&i.Reason,
			&i.Details,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReport = `-- name: UpdateReport :one
WITH updated AS (
    UPDATE reports
    SET status = $2, resolved_by = $3, resolved_at = now()
    WHERE reports.id = $1
    RETURNING id, reporter_id, reported_user_id, reason, details, status, resolved_by, resolved_at, create_time
)
SELECT
    updated.id,
    reporter.username AS reporter_username,
    reported.username AS reported_username,
    resolver.username AS resolved_by_username,
    updated.reason,
    updated.details,
    updated.status
FROM updated
INNER JOIN users reporter
    ON updated.reporter_id = reporter.id
LEFT JOIN users reported
    ON updated.reported_user_id = reported.id
LEFT JOIN users resolver
    ON updated.resolved_by = resolver.id
`

type UpdateReportParams struct {
	ID         pgtype.UUID `json:"id"`
	Status     int32       `json:"status"`
	ResolvedBy pgtype.UUID `json:"resolvedBy"`
}

type UpdateReportRow struct {
	ID                 pgtype.UUID `json:"id"`
	ReporterUsername   string      `json:"reporterUsername"`
	ReportedUsername   pgtype.Text `json:"reportedUsername"`
	ResolvedByUsername pgtype.Text `json:"resolvedByUsername"`
	Reason             string      `json:"reason"`
	Details            pgtype.Text `json:"details"`
	Status             int32       `json:"status"`
}

func (q *Queries) UpdateReport(ctx context.Context, arg UpdateReportParams) (UpdateReportRow, error) {
	row := q.db.QueryRow(ctx, updateReport, arg.ID, arg.Status, arg.ResolvedBy)
	var i UpdateReportRow
	err := row.Scan(
		&i.ID,
		&i.ReporterUsername,
		&i.ReportedUsername,
		&i.ResolvedByUsername,
		&i.Reason,
		&i.Details,
		&i.Status,
	)
	return i, err
}
