// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repost.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkRepost = `-- name: CheckRepost :one
SELECT EXISTS (
  SELECT 1 FROM reposts
WHERE user_id=$1 AND post_id=$2
)
`

type CheckRepostParams struct {
	UserID pgtype.UUID `json:"userId"`
	PostID pgtype.UUID `json:"postId"`
}

func (q *Queries) CheckRepost(ctx context.Context, arg CheckRepostParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkRepost, arg.UserID, arg.PostID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const repost = `-- name: Repost :one
INSERT INTO public.reposts
(user_id, post_id)
VALUES($1, $2)
RETURNING user_id, post_id
`

type RepostParams struct {
	UserID pgtype.UUID `json:"userId"`
	PostID pgtype.UUID `json:"postId"`
}

func (q *Queries) Repost(ctx context.Context, arg RepostParams) (Repost, error) {
	row := q.db.QueryRow(ctx, repost, arg.UserID, arg.PostID)
	var i Repost
	err := row.Scan(&i.UserID, &i.PostID)
	return i, err
}

const unRepost = `-- name: UnRepost :one
DELETE FROM public.reposts
WHERE user_id=$1 AND post_id=$2
RETURNING user_id, post_id
`

type UnRepostParams struct {
	UserID pgtype.UUID `json:"userId"`
	PostID pgtype.UUID `json:"postId"`
}

func (q *Queries) UnRepost(ctx context.Context, arg UnRepostParams) (Repost, error) {
	row := q.db.QueryRow(ctx, unRepost, arg.UserID, arg.PostID)
	var i Repost
	err := row.Scan(&i.UserID, &i.PostID)
	return i, err
}
