// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPendingEmail = `-- name: AddPendingEmail :exec
UPDATE users SET pending_email = $2
where id = $1 and is_delete = false
`

type AddPendingEmailParams struct {
	ID           pgtype.UUID
	PendingEmail pgtype.Text
}

func (q *Queries) AddPendingEmail(ctx context.Context, arg AddPendingEmailParams) error {
	_, err := q.db.Exec(ctx, addPendingEmail, arg.ID, arg.PendingEmail)
	return err
}

const confirmEmailChange = `-- name: ConfirmEmailChange :one
UPDATE users SET email = pending_email,
pending_email = null,
update_time = now()
where id = $1 and is_delete = false
RETURNING is_delete, create_time, update_time, id, username, email, avatar, password, role, email_verified, bio, name, pending_email
`

func (q *Queries) ConfirmEmailChange(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, confirmEmailChange, id)
	var i User
	err := row.Scan(
		&i.IsDelete,
		&i.CreateTime,
		&i.UpdateTime,
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Avatar,
		&i.Password,
		&i.Role,
		&i.EmailVerified,
		&i.Bio,
		&i.Name,
		&i.PendingEmail,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users
(id, username, email, password, name, role, is_delete, create_time)
VALUES (gen_random_uuid(), $1, $2, $3, $4, 'user', false, now())
RETURNING id
`

type CreateUserParams struct {
	Username string
	Email    string
	Password pgtype.Text
	Name     pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Name,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET is_delete = true,
update_time = now()
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT is_delete, create_time, update_time, id, username, email, avatar, password, role, email_verified, bio, name, pending_email FROM users WHERE id = $1 AND is_delete = false LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.IsDelete,
		&i.CreateTime,
		&i.UpdateTime,
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Avatar,
		&i.Password,
		&i.Role,
		&i.EmailVerified,
		&i.Bio,
		&i.Name,
		&i.PendingEmail,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, username, "name", email, avatar, bio, role from users
where is_delete = false and id = $1
`

type GetUserByIDRow struct {
	ID       pgtype.UUID
	Username string
	Name     pgtype.Text
	Email    string
	Avatar   pgtype.Text
	Bio      pgtype.Text
	Role     string
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.Avatar,
		&i.Bio,
		&i.Role,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT is_delete, create_time, update_time, id, username, email, avatar, password, role, email_verified, bio, name, pending_email FROM users
WHERE username = $1 AND is_delete = false LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.IsDelete,
		&i.CreateTime,
		&i.UpdateTime,
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Avatar,
		&i.Password,
		&i.Role,
		&i.EmailVerified,
		&i.Bio,
		&i.Name,
		&i.PendingEmail,
	)
	return i, err
}

const getUserByUsernameAndPassword = `-- name: GetUserByUsernameAndPassword :one
SELECT is_delete, create_time, update_time, id, username, email, avatar, password, role, email_verified, bio, name, pending_email FROM users
WHERE username = $1 AND password = $2 AND is_delete = false LIMIT 1
`

type GetUserByUsernameAndPasswordParams struct {
	Username string
	Password pgtype.Text
}

func (q *Queries) GetUserByUsernameAndPassword(ctx context.Context, arg GetUserByUsernameAndPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameAndPassword, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.IsDelete,
		&i.CreateTime,
		&i.UpdateTime,
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Avatar,
		&i.Password,
		&i.Role,
		&i.EmailVerified,
		&i.Bio,
		&i.Name,
		&i.PendingEmail,
	)
	return i, err
}

const getUserIDByUsername = `-- name: GetUserIDByUsername :one
SELECT id FROM users
WHERE username = $1 AND is_delete = false LIMIT 1
`

func (q *Queries) GetUserIDByUsername(ctx context.Context, username string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByUsername, username)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listUsers = `-- name: ListUsers :many
SELECT is_delete, create_time, update_time, id, username, email, avatar, password, role, email_verified, bio, name, pending_email FROM users WHERE is_delete = false and role = 'user' ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.IsDelete,
			&i.CreateTime,
			&i.UpdateTime,
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Avatar,
			&i.Password,
			&i.Role,
			&i.EmailVerified,
			&i.Bio,
			&i.Name,
			&i.PendingEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password = $2,
update_time = now()
where id = $1 and is_delete = false
`

type UpdatePasswordParams struct {
	ID       pgtype.UUID
	Password pgtype.Text
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.Password)
	return err
}

const updateUserNotIncludeEmail = `-- name: UpdateUserNotIncludeEmail :one
UPDATE users
SET
username = $2,
name = $3,
avatar = $4,
bio = $5,
update_time = now()
WHERE id = $1 AND is_delete = false
RETURNING is_delete, create_time, update_time, id, username, email, avatar, password, role, email_verified, bio, name, pending_email
`

type UpdateUserNotIncludeEmailParams struct {
	ID       pgtype.UUID
	Username string
	Name     pgtype.Text
	Avatar   pgtype.Text
	Bio      pgtype.Text
}

func (q *Queries) UpdateUserNotIncludeEmail(ctx context.Context, arg UpdateUserNotIncludeEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserNotIncludeEmail,
		arg.ID,
		arg.Username,
		arg.Name,
		arg.Avatar,
		arg.Bio,
	)
	var i User
	err := row.Scan(
		&i.IsDelete,
		&i.CreateTime,
		&i.UpdateTime,
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Avatar,
		&i.Password,
		&i.Role,
		&i.EmailVerified,
		&i.Bio,
		&i.Name,
		&i.PendingEmail,
	)
	return i, err
}

const userExistsByUsernameOrEmail = `-- name: UserExistsByUsernameOrEmail :one
SELECT EXISTS (
SELECT 1
FROM users
WHERE (username = $1 OR email = $2)
AND is_delete = false
)
`

type UserExistsByUsernameOrEmailParams struct {
	Username string
	Email    string
}

func (q *Queries) UserExistsByUsernameOrEmail(ctx context.Context, arg UserExistsByUsernameOrEmailParams) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByUsernameOrEmail, arg.Username, arg.Email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const verifyUser = `-- name: VerifyUser :exec
UPDATE users
SET email_verified = true, update_time = now()
WHERE id = $1 AND is_delete = false
`

func (q *Queries) VerifyUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyUser, id)
	return err
}
